#!/bin/bash -e

cd "$(dirname "$0")"

. ./config.sh

if [[ -f user-config.sh ]]
then
    . ./user-config.sh
fi

build()
{
    pushd "$1"
    ln -sf ../patch/* .
cat >system-config.cmake <<EOF
set(CMAKE_MODULE_PATH \${CMAKE_SOURCE_DIR}/../common)
set(ENABLE_TESTS ${ENABLE_TESTS:-no})
set(CMAKE_BUILD_TYPE ${BUILD_TYPE:-Release})
set(CMAKE_INSTALL_PREFIX ${INSTALL_PREFIX:-/usr})
set(CMAKE_CXX_COMPILER ${CXX_COMPILER:-/usr/bin/g++-4.7})
set(CMAKE_C_COMPILER ${C_COMPILER:-/usr/bin/gcc-4.7})
foreach(proj ${libs[*]})
    include_directories(\${CMAKE_SOURCE_DIR}/../\${proj}/include)
    link_directories(\${CMAKE_SOURCE_DIR}/../\${proj}/build)
endforeach()
EOF
    if [[ -d java ]]
    then
        pushd java
        mvn package -DskipTests
        popd
        ./jni_gen.sh
        ./jni_validate.sh
    fi
    mkdir -p build
    cd build
    cmake ..
    make
    popd
}

for i in "${libs[@]}"
do
    build "$i"
done
