#!/bin/bash -e

cd "$(dirname "$0")"

. ./config.sh

clean()
{
    if [[ -d $1 ]]
    then
        pushd "$1"
        git reset --hard
        git status --porcelain | egrep '^\?\? ' | sed -r 's|^...||' | xargs -d '\n' rm -rf
        popd
    fi
}

while getopts "frh" arg
do
    case "$arg" in
        f) force=1 ;;
        r) recursive=1 ;;
        h) ;;&
        ?) printf "Usage: %s: [-r recursive] [-f ignore repack]\n" "$0" 1>&2 && exit 1;;
    esac
done
shift $((OPTIND - 1))

if [[ $repack && -z $force ]]
then
    exit 0
fi

if [[ $recursive ]]
then
    rm -rf "${alllibs[@]}"
else
    for i in "${alllibs[@]}"
    do
        clean "$i"
    done
fi
