#!/bin/bash -e

cd "$(dirname "$0")"

. ./config.sh

./clean -f

fetch()
{
    if [[ -d $1 ]]
    then
        pushd "$1"
        git fsck
        git pull
        popd
    else
        git clone "$repo/$1.git" "$1"
    fi
}

for i in "${alllibs[@]}"
do
    fetch "$i"
done
