#!/bin/bash -e

command_if()
{
    local regex="$1"
    shift
    if svn status | egrep "$regex" &>/dev/null
    then
        svn status | egrep "$regex" | sed -r 's|^[^[:space:]]+[[:space:]]+([^[:space:]].*)$|\1|' | xargs "$@"
    fi
}

command_if '^!' svn delete
svn add --force --depth=infinity .
command_if '\.git' svn commit --non-recursive --message "Invoker update (.git files)." "$@"
exec svn commit
